# Generated by Django 3.1.1 on 2020-11-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafarnamaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='img',
        ),
        migrations.RemoveField(
            model_name='super',
            name='name',
        ),
        migrations.AddField(
            model_name='super',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='super',
            name='hotel',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='super',
            name='img1',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='super',
            name='img2',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='super',
            name='img3',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='super',
            name='img4',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='super',
            name='off',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='super',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
