# Generated by Django 3.1.1 on 2020-11-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafarnamaApp', '0002_auto_20201123_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='super',
            name='img4',
        ),
        migrations.AddField(
            model_name='super',
            name='tax',
            field=models.IntegerField(default=None),
        ),
    ]
