# Generated by Django 3.1.1 on 2020-11-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafarnamaApp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
